[metadata]
name = arraypicture
version = 0.1.0
description = WinAPI ArrayPicture control (CPython C-API)
author = G. Shabanov
license = MIT

[options]
packages = find:
package_dir =
    = src
zip_safe = false

[options.packages.find]
where = src

[options.package_data]
arraypicture = *.h

[options.extras_require]
dev =

[build_ext]
# for MSVC: /std:c++17 and hard warnings

[bdist_wheel]
universal = 0
